In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.datasets import load_diabetes

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
X.shape

(442, 10)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

### **MAKING LR CLASS MYSELF !!!!**

In [49]:
class MeraLR:

    def __innit__(self):
       self.coef_ = None
       self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train= np.insert(X_train,0,1,axis=1)

        #calculate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        print(betas)

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

np.insert is the function that helps us insert what we want with syntax like

np.insert(X_train,indexnumber,number,axis)

In [50]:
lr = MeraLR()

In [51]:
lr.fit(X_train,y_train)

[ 153.13441535   -1.13744712 -212.8867836   540.45536994  345.20621542
 -938.23814645  516.62060367  172.85885498  267.87535242  732.63230159
   70.07849485]


In [52]:
X_train.shape

(353, 10)

In [53]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [54]:
lr.intercept_

153.13441535285006

In [56]:
y_pred = lr.predict(X_test)

In [60]:
print("MAE =",mean_absolute_error(y_test,y_pred))
print("MSE =",mean_squared_error(y_test,y_pred))
print("RMSE =",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2 score =",r2_score(y_test,y_pred))

MAE = 44.84820711311209
MSE = 3161.213140359926
RMSE = 56.22466665405786
r2 score = 0.4161792211496943


In [57]:
r2_score(y_test,y_pred)

0.4161792211496943

In [58]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [61]:
lr.intercept_

153.13441535285006